% This file will read desired VenusGRAM inputs (from a csv file for example) and
% generate GRAM-readable input.txt files.
% Just specify the relevant directories and csv file with iteration
% schedule. After generating inputs using this script, another script to
% automatically run VenusGRAM for all input files can be run.
clear
clc

%% INPUTS ---------
csvfile = 'D:\Documents\GRAMsuite\Venus\iterations\Venus_LatLon_iterations.xlsx';
InputDir = 'D:\Documents\GRAMsuite\Venus\inputs';
OutputDir = 'D:\Documents\GRAMsuite\Venus\results\';
DataDir = 'D:\Documents\GRAMsuite\Venus\';

%% -------------
% reading the iteration table
fprintf('Reading iterations...\n')
iter = readtable(csvfile);
IterationID = cell2mat(iter.IterationID);
Myear = iter.Year;
Month = iter.Month;
Mday = iter.Day;
Ihr = iter.Hour;
Imin = iter.Minute;
Sec = iter.Sec;
NPoints = iter.NoOfPoints;
start_lat = iter.lat;
start_lon = iter.lon;
start_h = iter.h_km;
dh = iter.dh_km;
dlat = iter.dlat;
dlon = iter.dlon;
dt = iter.dt_sec;
[r,~] = size(iter);

fprintf('Generating VenusGRAM input files...\n')
for i = 1:r % create input file for each i-th iteration
    
    % Specify directories and formatted filenames:
    InputFile  = fullfile(InputDir,sprintf('INPUT_%s.txt',IterationID(i,:)));
    OutputFile = fullfile(OutputDir,sprintf('OUTPUT_%s.txt',IterationID(i,:)));
    ListFile = fullfile(OutputDir,sprintf('LIST_%s.txt',IterationID(i,:)));

    FileContent = FormatVenusGRAMInput(ListFile,OutputFile,DataDir,1,1,Month(i),Mday(i),Myear(i),Ihr(i),Imin(i),Sec(i),...
        NPoints(i),1,1234,1,0,0,start_lat(i),start_lon(i),start_h(i),dh(i),dlat(i),dlon(i),dt(i),...
        0,0,1.0,1,13,0.0);

    InputFID = fopen(InputFile,'w');
    fprintf(InputFID,'%s',FileContent);
    fclose(InputFID);
    
end
fprintf('Completed! All input files are saved...\n')   
%----function definition-----------------------------    
function[ToWrite] = FormatVenusGRAMInput(ListFile,OutputFile,DataDir,IERT,IUTC,Month,Mday,Myear,Ihr,Imin,Sec,...
        NPOS,LonEast,NR1,NVARX,NVARY,LOGSCALE,FLAT,FLON,FHGT,dh,dlat,dlon,dt,...
        profnear,proffar,rpscale,NMONTE,iup,corlmin)
% This function formats Input file content for use with VenusGRAM     
    
% Format input file contents:
ToWrite = sprintf(['$INPUT\n',...                                           
  ' LSTFL     = ''%s'' \n',...     % filename for list.txt file        
  ' OUTFL     = ''%s'' \n',...     % filename for output.txt file
  ' DATADIR   = ''%s'' \n',...     % dir where VIRA coefficients are stored
  ' IERT      = %d \n',...         % 1-> Earth Receive Time, 0-> Venus Event Time
  ' IUTC      = %d \n',...         % 1-> UTC, 0-> Terrestrial Time
  ' Month     = %d \n',...         % Month of year
  ' Mday      = %d \n',...         % Day of month
  ' Myear     = %d \n',...         % Year (1970-2069 can be 2 digit else 4 digit)
  ' Ihr       = %d \n',...         % Hour of day
  ' Imin      = %d \n',...         % Minute of hour
  ' Sec       = %.1f \n',...         % Sec of minute
  ' NPOS      = %d \n',...         % No of data points to evaluate
  ' LonEast   = %d \n',...         % 1-> +ve East
  ' NR1       = %d \n',...         % Start random number (0<NR1<30000)
  ' NVARX     = %d \n',...         % code for plottabe output
  ' NVARY     = %d \n',...         % code for plottable second output (leave 0 if not desired)
  ' LOGSCALE  = %d \n',...         % 0 -> regular SI units
  ' FLAT      = %.1f \n',...         % start latitude (N is +ve) (deg)
  ' FLON      = %.1f \n',...         % start longitude (LonEast convention) (deg)
  ' FHGT      = %.1f \n',...         % start height (km)
  ' DELHGT    = %.1f \n',...         % height increment between datapoints (km)
  ' DELLAT    = %.1f \n',...         % lat increment (deg)
  ' DELLON    = %.1f \n',...         % lon increment (deg)
  ' DELTIME   = %.1f \n',...         % time increment (sec)
  ' profnear  = %.1f \n',...         % set 0 fo no profile input       
  ' proffar   = %.1f \n',...         % set 0
  ' rpscale   = %.1f \n',...         % random perturbation scale factor, leave as 1.0
  ' NMONTE    = %d \n',...         % No of Monte Carlo runs (leave as 1)
  ' iup       = %d \n',...         % leave 13 as default
  ' corlmin   = %.1f \n',...         % leave 0 as default
 '$END\n\n',...
 'Explanation of variables:\n',... % need to write this verbose explainer too
  'LSTFL     =  List file name (CON for console listing)\n',... 
  'OUTFL     =  Output file name\n',... 
  'TRAJFL    =  (Optional) Trajectory input file name\n',...
  'profile   =  (Optional) auxiliary profile input file name\n',...
  'DATADIR   =  Directory for VIRA input data\n',... 
  'IERT      =  1 for time input as Earth-receive time (ERT), or 0 Venus-event time (VET)\n',...
  'IUTC      =  1 for time input as Coordinated Universal Time (UTC), or 0 for Terrestrial (Dynamical) Time (TT)\n',...
  'MONTH     =  month of year\n',...                         
  'MDAY      =  day of month\n',...                    
  'MYEAR     =  year (4-digit, or 1970-2069 can be 2-digit)\n',...
  'IHR       =  Hour of day (ERT or VET, controlled by IERT and UTC or TT, controlled by IUTC)\n',... 
  'IMIN      =  minute of hour (meaning controlled by IERT and IUTC)\n',...                                       
  'SEC       =  seconds of minute (meaning controlled by IERT and IUTC).  IHR:IMIN:SEC is time for initial position to be evaluated\n',...                 
  'NPOS      =  max # positions to evaluate (0 = read data from trajectory input file)\n',... 
  'LonEast   =  1 for East longitudes positive (default); 0 for input and output West longitudes positive;\n',...
  'NR1       =  starting random number (0 < NR1 < 30000)\n',... 
  'NVARX     =  x-code for plotable output (1=height above reference ellipsoid). See file xycodes.txt\n',...
  'NVARY     =  y-code for 2-D plotable output (0 for 1-D plots)\n',...
  'LOGSCALE  =  0=regular SI units, 1=log-base-10 scale, 2=percentagedeviations from Mean model, 3=SI units with density in kg/km**3\n',... 
  'FLAT      =  initial latitude (N positive), degrees\n',...  
  'FLON      =  initial longitude (West positive if LonEast=0 or East positive if LonEast = 1), degrees\n',... 
  'FHGT      =  initial height (km)\n',...  
  'DELHGT    =  height increment (km) between steps\n',...
  'DELLAT    =  latitude increment (deg) between steps\n',...        
  'DELLON    =  longitude increment (deg) between steps (West positive if LonEast = 0, East positive if LonEast = 1)\n',...      
  'DELTIME   =  time increment (seconds) between steps.  Time increment is in ERT or VET, as controlled by input parameter IERT, and UTC or TT, as controlled by input parameter IUTC\n',... 
  'profnear  =  Lat-lon radius (degrees) within which weight for auxiliary  profile is 1.0 (Use profnear = 0.0 for no profile input)\n',...
  'proffar   =  Lat-lon radius (degrees) beyond which weight for auxiliary profile is 0.0\n',...
  'rpscale   =  random perturbation scale factor (0-2)\n',...    
  'NMONTE    =  number of Monte Carlo runs\n',...            
  'iup       =  0 for no LIST and graphics output, unit number for LIST file otherwise\n',... 
  'corlmin   =  Minimum relative step size for perturbations (0.0 - 1.0); 0.0 means always update perturbations, x.x means only update perturbations when corlim > x.x\n'],...
        ListFile,OutputFile,DataDir,IERT,IUTC,Month,Mday,Myear,Ihr,Imin,Sec,...
        NPOS,LonEast,NR1,NVARX,NVARY,LOGSCALE,FLAT,FLON,FHGT,dh,dlat,dlon,dt,...
        profnear,proffar,rpscale,NMONTE,iup,corlmin);
    
end
  
 
