% This file will read desired VenusGRAM inputs (from a csv file for example) and
% generate GRAM-readable input.txt files.
% Just specify the relevant directories and csv file with iteration
% schedule. After generating inputs using this script, another script to
% automatically run VenusGRAM for all input files can be run.
clear
clc

%% INPUTS ---------
csvfile = 'D:\Documents\GRAMsuite\Mars\Release1.0_Nov10\RunResults\MCS_demo\Mars_MCS_demo.xlsx'; % iteration schedule
InputDir = 'D:\Documents\GRAMsuite\Mars\Release1.0_Nov10\RunResults\MCS_demo\Inputs'; % Folder where input files to MarsGRAM will be saved
OutputDir = 'D:\Documents\GRAMsuite\Mars\Release1.0_Nov10\RunResults\MCS_demo\Outputs'; % Output files to be saved here after running MarsGRAM
MiscDir = 'D:\Documents\GRAMsuite\Mars\Release1.0_Nov10\RunResults\MCS_demo\Misc'; % folder for non-important outputs
DataDir = 'D:\Documents\GRAMsuite\Mars\Release1.0_Nov10\binFiles\'; % where MarsGRAM data coefficients reside
%% -------------
% reading the iteration table
fprintf('Reading iterations...\n')
iter = readtable(csvfile);
IterationID = cell2mat(iter.IterationID);
Myear = iter.Year;
Month = iter.Month;
Mday = iter.Day;
Ihr = iter.Hour;
Imin = iter.Minute;
Sec = iter.Sec;
NPoints = iter.NoOfPoints;
start_lat = iter.lat;
start_lon = iter.lon;
start_h = iter.h_km;
dh = iter.dh_km;
dlat = iter.dlat;
dlon = iter.dlon;
dt = iter.dt_sec;
[r,~] = size(iter);

fprintf('Generating MarsGRAM input files...\n')
for i = 1:r % create input file for each i-th iteration
    
    % Specify directories and formatted filenames:
    InputFile  = fullfile(InputDir,sprintf('INPUT_%s.txt',IterationID(i,:)));
    OutputFile = fullfile(OutputDir,sprintf('OUTPUT_%s.txt',IterationID(i,:)));
    ListFile = fullfile(OutputDir,sprintf('LIST_%s.txt',IterationID(i,:)));

    FileContent = FormatMarsGRAMInput(ListFile,OutputFile,MiscDir,DataDir,1,1,Month(i),Mday(i),Myear(i),Ihr(i),Imin(i),Sec(i),...
        NPoints(i),1,110,1234,1,0,0,start_lat(i),start_lon(i),start_h(i),1,dh(i),dlat(i),dlon(i),dt(i),...
        0,0,1.0,1,13,0.0);

    InputFID = fopen(InputFile,'w');
    fprintf(InputFID,'%s',FileContent);
    fclose(InputFID);
    
end
fprintf('Completed! All input files are saved...\n')   
%----function definition-----------------------------    
function[ToWrite] = FormatMarsGRAMInput(ListFile,OutputFile,MiscDir,DataDir,IERT,IUTC,Month,Mday,Myear,Ihr,Imin,Sec,...
        NPOS,LonEast,F107,NR1,NVARX,NVARY,LOGSCALE,FLAT,FLON,FHGT,MOLAHgts,dh,dlat,dlon,dt,...
        profnear,proffar,rpscale,NMONTE,iup,corlmin)
% This function formats Input file content for use with VenusGRAM     
    
% Format input file contents:
ToWrite = sprintf(['$INPUT_M10\n',...                                           
  ' LSTFL     = ''%s'' \n',...     % filename for list.txt file        
  ' OUTFL     = ''%s'' \n',...     % filename for output.txt file
  ' TRAJFL   = ''%s'' \n',...     % dir where trajectory points are stored
  ' profile  = ''null'' \n',...
  ' WaveFile = ''null'' \n',...
  ' DATADIR  = ''%s'' \n',...
  ' GCMDIR   = ''%s'' \n',...
  ' IERT      = %d \n',...         % 1-> Earth Receive Time, 0-> Venus Event Time
  ' IUTC      = %d \n',...         % 1-> UTC, 0-> Terrestrial Time
  ' Month     = %d \n',...         % Month of year
  ' Mday      = %d \n',...         % Day of month
  ' Myear     = %d \n',...         % Year (1970-2069 can be 2 digit else 4 digit)
  ' Ihr       = %d \n',...         % Hour of day
  ' Imin      = %d \n',...         % Minute of hour
  ' Sec       = %.1f \n',...         % Sec of minute
  ' NPOS      = %d \n',...         % No of data points to evaluate
  ' LonEW   = %d \n',...         % 1-> +ve East
  ' Dusttau  = 0.3 \n',...          % Leaving dust parameters as default
  ' Dustmin  = 0.3 \n',...
  ' Dustmax  = 1.0 \n',...
  ' Dustnu   = 0.003 \n',...
  ' Dustdiam = 5.0 \n',...
  ' Dustdens = 3000. \n',...
  ' ALS0     = 0.0 \n',...
  ' ALSDUR   = 48. \n',...
  ' INTENS   = 0.0 \n',...
  ' RADMAX   = 0.0 \n',...
  ' DUSTLAT  = 0.0 \n',...
  ' DUSTLON  = 0.0 \n',...
  ' MapYear  = 0 \n',...
  ' F107     =  %d \n',...        %10.7 cm solar flux (10**-22 W/cm**2 at 1 AU)
  ' NR1       = %d \n',...         % Start random number (0<NR1<30000)
  ' NVARX     = %d \n',...         % code for plottabe output
  ' NVARY     = %d \n',...         % code for plottable second output (leave 0 if not desired)
  ' LOGSCALE  = %d \n',...         % 0 -> regular SI units
  ' FLAT      = %.1f \n',...         % start latitude (N is +ve) (deg)
  ' FLON      = %.1f \n',...         % start longitude (LonEast convention) (deg)
  ' FHGT      = %.1f \n',...         % start height (km)
  ' MOLAhgts =  %d \n',...      % for input heights relative to MOLA areoid, otherwise input heights are relative to reference ellipsoid
  ' hgtasfcm = 0. \n',...       % height above surface (0-4500 m); use if FHGT <= -10. km
  ' zoffset  = 0 \n',...     % constant height offset (km) for MTGCM data or constant part of Ls-dependent (Bougher) height offset
  ' ibougher = 0 \n',...
  ' DELHGT    = %.1f \n',...         % height increment between datapoints (km)
  ' DELLAT    = %.1f \n',...         % lat increment (deg)
  ' DELLON    = %.1f \n',...         % lon increment (deg)
  ' DELTIME   = %.1f \n',...         % time increment (sec)
  ' deltaTEX = 0.0 \n',...              %  adjustment for exospheric temperature (K)
  ' profnear  = %.1f \n',...         % set 0 fo no profile input       
  ' proffar   = %.1f \n',...         % set 0
  ' rpscale   = %.1f \n',...         % random perturbation scale factor, leave as 1.0
  ' rwscale  = 1.0 \n',...           % random wind perturbation scale factor (>=0)
  ' wlscale  = 1.0 \n',...           % scale factor for perturbation wavelengths (0.1-10)
  ' wmscale  = 1.0 \n',...           % scale factor for mean winds
  ' blwinfac = 1.0 \n',...           % scale factor for boundary layer slope winds (0 = none)
  ' NMONTE    = %d \n',...         % No of Monte Carlo runs (leave as 1)
  ' iup       = %d \n',...         % leave 13 as default
  ' WaveA0   = 1.0 \n',... 
  ' WaveDate = 0.0 \n',... 
  ' WaveA1   = 0.0 \n',... 
  ' Wavephi1 = 0.0 \n',... 
  ' phi1dot  = 0.0 \n',... 
  ' WaveA2   = 0.0 \n',... 
  ' Wavephi2 = 0.0 \n',... 
  ' phi2dot  = 0.0 \n',... 
  ' WaveA3   = 0.0 \n',... 
  ' Wavephi3 = 0.0 \n',... 
  ' phi3dot  = 0.0 \n',... 
  ' iuwave   = 0 \n',... 
  ' Wscale   = 20. \n',... 
  ' corlmin   = %.1f \n',...         % leave 0 as default
  ' ipclat   = 1 \n',...            % 1 for Planeto-centric (0 for planetographic) latitude and height input
  ' requa    = 3396.19 \n',...      % Equatorial radius (km) for reference ellipsoid
  ' rpole    = 3376.20 \n',...      % Polar radius (km) for reference ellipsoid
  ' idaydata = 1 \n',...            % 1 for daily max/min data output; 0 for none
 '$END\n\n',...
 'Explanation of variables:\n',... % need to write this verbose explainer too
 'LSTFL    =  List file name (CON for console listing)\n',...
 'OUTFL    =  Output file name\n',...
 'TRAJFL   =  (Optional) Trajectory input file. File contains time (sec) relative to start time, height (km), latitude (deg),longitude (deg W if LonEW=0, deg E if LonEW=1, see below)\n',...
 'profile  =  (Optional) auxiliary profile input file name\n',...              
 'WaveFile =  (Optional) file for time-dependent wave coefficient data. See file description under parameter iuwave.\n',...
 'DATADIR  =  Directory for COSPAR data and topographic height data\n',... 
 'GCMDIR   =  Directory for GCM binary data files\n',...
 'IERT     =  1 for time input as Earth-Receive time (ERT) or 0 Mars-event time (MET)\n',...
 'IUTC     =  1 for time input as Coordinated Universal Time (UTC), or 0 for Terrestrial (Dynamical) Time (TT)\n',...
 'MONTH    =  (Integer) month of year\n',...
 'MDAY     =  (Integer) day of month\n',...
 'MYEAR    =  (Integer) year (4-digit; 1970-2069 can be 2-digit)\n',...
 'NPOS     =  max # positions to evaluate (0 = read data from trajectory input file)\n',...
 'IHR      =  Hour of day (ERT or MET, controlled by IERT and UTC or TT, controlled by IUTC)\n',...
 'IMIN     =  minute of hour (meaning controlled by IERT and IUTC)\n',...
 'SEC      =  seconds of minute (meaning controlled by IERT and IUTC). IHR:IMIN:SEC is time for initial position to be evaluated\n',...
 'LonEW    =  0 for input and output West longitudes positive; 1 for East longitudes positive\n',...
 'Dusttau  =  Optical depth of background dust level (no time-developing dust storm, just uniformly mixed dust), 0.1 to 3.0, or use0 for assumed seasonal variation of background dust\n',...
 'Dustmin  =  Minimum seasonal dust tau if input Dusttau=0 (>=0.1)\n',...
 'Dustmax  =  Maximum seasonal dust tau if input Dusttau=0 (<=1.0)\n',...
 'Dustnu   =  Parameter for vertical distribution of dust density (Haberleet al., J. Geophys. Res., 104, 8957, 1999)\n',...
 'Dustdiam =  Dust particle diameter (micrometers, assumed monodisperse)\n',...
 'Dustdens =  Dust particle density (kg/m**3)\n',...
 'ALS0     =  starting Ls value (degrees) for dust storm (0 = none)\n',...
 'ALSDUR   =  duration (in Ls degrees) for dust storm (default = 48)\n',...
 'INTENS   =  dust storm intensity (0.0 - 3.0)\n',...
 'RADMAX   =  max. radius (km) of dust storm (0 or >10000 = global)\n',...
 'DUSTLAT  =  Latitude (degrees) for center of dust storm\n',...
 'DUSTLON  =  Longitude (degrees) (West positive if LonEW=0, or East positive if LonEW = 1) for center of dust storm\n',...
 'MapYear  =  1 or 2 for TES mapping year 1 or 2 GCM input data, or 0 for Mars-GRAM 2001 GCM input data sets\n',...           
 'F107     =  10.7 cm solar flux (10**-22 W/cm**2 at 1 AU)\n',...
 'NR1      =  starting random number (0 < NR1 < 30000)\n',...
 'NVARX    =  x-code for plotable output (1=hgt above MOLA areoid).See file xycodes.txt\n',...
 'NVARY    =  y-code for 3-D plotable output (0 for 2-D plots)\n',...
 'LOGSCALE =  0=regular SI units, 1=log-base-10 scale, 2=percentage deviations from COSPAR model, 3=SI units, with densityin kg/km**3 (suitable for high altitudes)\n',...
 'FLAT     =  initial latitude (N positive), degrees\n',...
 'FLON     =  initial longitude (West positive if LowEW = 0 or Eastpositive if LonEW = 1), degrees\n',...
 'FHGT     =  initial height (km); <=-10 means evaluate at surface height;> 3000 km means planeto-centric radius\n',...
 'MOLAhgts =  1 for input heights relative to MOLA areoid, otherwise input heights are relative to reference ellipsoid\n',...
 'hgtasfcm =  height above surface (0-4500 m); use if FHGT <= -10. km\n',...
 'zoffset  =  constant height offset (km) for MTGCM data or constantpart of Ls-dependent (Bougher) height offset (0.0 means no constant offset).  Positive offset increases density, negative offset decreases density.\n',...
 'ibougher =  0 for no Ls-dependent (Bougher) height offset term; 1 means add Ls-dependent (Bougher) term, -A*Sin(Ls) (km), to constant term (zoffset) [offset amplitude A = 2.5 for MapYear=0 or 0.5 for MapYear > 0]; 2 means use global mean\n',...
             'height offset from data file hgtoffst.dat; 3 means use\n',...
             'daily average height offset at local position; 4 means\n',...
             'use height offset at current time and local position.\n',...
             'Value of zoffset is ignored if ibougher = 2, 3, or 4.\n',...
 'DELHGT   =  height increment (km) between steps\n',...
 'DELLAT   =  Latitude increment (deg) between steps (Northward positive)\n',...
 'DELLON   =  Longitude increment (deg) between steps (Westward positiveif LonEW = 0, Eastward positive if LonEW = 1)\n',...
 'DELTIME  =  time increment (sec) between steps\n',...
 'deltaTEX =  adjustment for exospheric temperature (K)\n',...
 'profnear =  Lat-lon radius (degrees) within which weight for auxiliary  profile is 1.0 (Use profnear = 0.0 for no profile input)\n',...
 'proffar  =  Lat-lon radius (degrees) beyond which weight for auxiliary profile is 0.0\n',...
 'rpscale  =  random density perturbation scale factor (0-2)\n',...
 'rwscale  =  random wind perturbation scale factor (>=0)\n',...
 'wlscale  =  scale factor for perturbation wavelengths (0.1-10)\n',...
 'wmscale  =  scale factor for mean winds\n',...
 'blwinfac =  scale factor for boundary layer slope winds (0 = none)\n',...
 'NMONTE   =  number of Monte Carlo runs\n',...
 'iup      =  0 for no LIST and graphics output, or unit number for output\n',...
 'WaveA0   =  Mean term of longitude-dependent wave multiplier for density\n',...
 'WaveDate =  Julian date for (primary) peak(s) of wave (0 for no traveling component) \n',...
 'WaveA1   =  Amplitude of wave-1 component of longitude-dependent wave multiplier for density\n',...
 'Wavephi1 =  Phase of wave-1 component of longitude-dependent wave multiplier (longitude, with West positive if LonEW = 0,East positive if LonEW = 1)\n',...
 'phi1dot  =  Rate of longitude movement (degrees per day) for wave-1 component (Westward positive if LonEW = 0, Eastward  positive if LonEW = 1)\n',...
 'WaveA2   =  Amplitude of wave-2 component of longitude-dependent wave multiplier for density\n',...
 'Wavephi2 =  Phase of wave-2 component of longitude-dependent wave multiplier (longitude, with West positive if LonEW = 0, East positive if LonEW = 1)\n',...
 'phi2dot  =  Rate of longitude movement (degrees per day) for wave-2 component (Westward positive if LonEW = 0, Eastward positive if LonEW = 1)\n',...
 'WaveA3   =  Amplitude of wave-3 component of longitude-dependent wave multiplier for density\n',...
 'Wavephi3 =  Phase of wave-3 component of longitude-dependent wavemultiplier (longitude, with West positive if LonEW = 0, East positive if LonEW = 1)\n',...
 'phi3dot  =  Rate of longitude movement (degrees per day) for wave-3 component (Westward positive if LonEW = 0, Eastward positive if LonEW = 1)\n',...
 'iuwave   =  Unit number for (Optional) time-dependent wave coefficientdata file "WaveFile" (or 0 for none).\n',...WaveFile contains time (sec) relative to start time, andwave model coefficients (WaveA0 thru Wavephi3) from thegiven time to the next time in the data file.\n',...
 'Wscale   =  Vertical scale (km) of longitude-dependent wave damping at altitudes below 100 km (10<=Wscale<=10,000 km)\n',...
 'corlmin  =  minimum relative step size for perturbation updates(0.0-1.0); 0.0 means always update perturbations, x.xmeans only update perturbations when corlim > x.x\n',...
 'ipclat   =  1 for Planeto-centric latitude and height input, 0 for Planeto-graphic latitude and height input\n',...
 'requa    =  Equatorial radius (km) for reference ellipsoid\n',...
 'rpole    =  Polar radius (km) for reference ellipsoid\n',...
 'idaydata =  1 for daily max/min data output; 0 for none\n'],...
        ListFile,OutputFile,MiscDir,DataDir,DataDir,IERT,IUTC,Month,Mday,Myear,Ihr,Imin,Sec,...
        NPOS,LonEast,F107,NR1,NVARX,NVARY,LOGSCALE,FLAT,FLON,FHGT,MOLAHgts,dh,dlat,dlon,dt,...
        profnear,proffar,rpscale,NMONTE,iup,corlmin);
    
end
  
 
